name: release-flow

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

env:
  binary: releasable

jobs:
  build-linux:
    runs-on: ubuntu-latest

    steps:
      # - name: Get the version
      #   id: get_version
      #   run: echo "name=VERSION::${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - name: Build and release
        run: |
          cargo build --release
          strip target/release/${{ env.binary }}
      - uses: papeloto/action-zip@v1
        with:
          files: target/release/${{ env.binary }}
          dest: ${{ env.binary }}-linux.zip
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.binary }}-linux.zip
          asset_name: ${{ env.binary }}-linux-${{ GITHUB_REF#refs/tags/ }}.zip
          tag: ${{ github.ref }}
          overwrite: true
