name: release-flow

on:
  push:
    tags:
      - "[0-9]+.[0-9]+.[0-9]+*"

env:
  binary: releasable
  itch_name: wotm

jobs:
  build-linux:
    runs-on: ubuntu-latest
    env:
      channel: linux
    steps:
      - name: Get the version
        id: get_version
        run: echo ::set-output name=VERSION::${GITHUB_REF#refs/tags/}
      - uses: actions/checkout@v2
      - uses: actions-rs/toolchain@v1
        with:
          toolchain: stable
          override: true
      - uses: actions/cache@v2
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ env.channel }}-${{ hashFiles('**/Cargo.lock') }}
      - name: Build and release
        run: |
          cargo build --release
          strip target/release/${{ env.binary }}
      - uses: papeloto/action-zip@v1
        with:
          files: target/release/${{ env.binary }}
          dest: ${{ env.binary }}.zip
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          file: ${{ env.binary }}.zip
          asset_name: ${{ env.binary }}-${{ env.channel }}-${{ steps.get_version.outputs.VERSION }}.zip
          tag: ${{ github.ref }}
          overwrite: true
      - uses: josephbmanley/butler-publish-itchio-action@master
        env:
          BUTLER_CREDENTIALS: ${{ secrets.BUTLER_CREDENTIALS }}
          CHANNEL: ${{ env.channel }}
          ITCH_GAME: ${{ env.itch_name }}
          ITCH_USER: vleue
          PACKAGE: ${{ env.binary }}.zip
          VERSION: ${{ steps.get_version.outputs.VERSION }}
